@url = https://discountfinder.api.albertevallentin.dk/api
@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBbGJlcnRlIFZhbGxlbnRpbiIsInN1YiI6ImFAYS5kayIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzM1MTQ5NTM1LCJlbWFpbCI6ImFAYS5kayJ9.T51ilElI_WNmByBqhLiTeooxxNjoPD7D25w1taEwaIo

### 
POST {{url}}/auth/register/
Accept: application/json
Content-Type: application/json

{
    "email": "a@a.dk",
    "password": "a"
}



###
POST {{url}}/auth/login/
Content-Type: application/json
Accept: application/json

{
  "email": "a@a.dk",
  "password": "a"
}


###
GET {{url}}/stores
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/stores/59
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/postal_code/2800
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Get all stores
GET {{url}}/stores
Authorization: Bearer {{jwt_token}}

### Get specific store (id: 59)
GET {{url}}/stores/10
Authorization: Bearer {{jwt_token}}

### Get stores by postal code
GET {{url}}/stores/postal_code/2800
Authorization: Bearer {{jwt_token}}

### Add store to favorites
POST {{url}}/stores/16/favorite
Authorization: Bearer {{jwt_token}}

### Remove store from favorites
DELETE {{url}}/stores/16/favorite
Authorization: Bearer {{jwt_token}}

### Get all favorites
GET {{url}}/stores/favorites
Authorization: Bearer {{jwt_token}}